FROM apache/hive:4.0.0-beta-1

USER root
RUN set -ex; \
    apt-get update; \
    apt-get -y install wget; \
    rm -rf /var/lib/apt/lists/*

RUN wget https://jdbc.postgresql.org/download/postgresql-42.6.0.jar
RUN mv postgresql-42.6.0.jar /opt/hive/lib/.

USER hive