FROM apache/hive:4.0.0-beta-1

USER root
RUN set -ex; \
    apt-get update; \
    apt-get -y install wget; \
    rm -rf /var/lib/apt/lists/*

RUN wget https://jdbc.postgresql.org/download/postgresql-42.6.0.jar
RUN mv postgresql-42.6.0.jar /opt/hive/lib/.
RUN wget https://repo1.maven.org/maven2/org/apache/hadoop/hadoop-common/3.3.6/hadoop-common-3.3.6.jar
RUN mv hadoop-common-3.3.6.jar /opt/hive/lib/.

COPY picklejars/gcs-connector-hadoop3-latest.jar /opt/hive/lib/.
COPY picklejars/hadoop-aws-* /opt/hive/lib/.
COPY picklejars/aws-java-sdk-bundle-* /opt/hive/lib/.

COPY hive-site.xml /opt/hive/conf/.

USER hive
